baseURL: /
languageCode: en-gb
defaultContentLanguage: en
title: "Kamaete: Karate at Home"
theme: cupper-hugo-theme
googleAnalytics: ""
disqusShortname: ""
enableGitInfo: true
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: ""
  homeMetaContent: ""
  footer: Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). Deployed to [GitHub](https://github.com/kamaete.github.io).
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Mon, 02 Jan 06
  codePenUser: ""
  katex: true

menu:
  nav:
    #- name: Home
    #  url: /
    #  weight: 1
    #- name: Blog
    #  url: /post/
    #  weight: 2
    #- name: Resources
    #  url: /resources/
    #  weight: 3
    #- name: Tags
    #  url: /tags/
    #  weight: 4
    #- name: About
    #  url: /about/
    #  weight: 5
    - name: Home
      url: /
      weight: 1
    - name: Forest Dojo
      url: /forest-dojo/
      weight: 2
    - name: Stripes
      url: /stripes/
      weight: 3
    - name: Challenges/Badges
      url: /challenges/
      weight: 4
    - name: Kata
      url: /kata/
      weight: 5
    - name: Kicks
      url: /kicks/
      weight: 6
    - name: Weapons
      url: /weapons/
      weight: 7

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
